siteConfig:
  title: NS Links
  desc: A list of links to help people serving National Service in Singapore.

permalinks:
  # post: /posts/:slug
  post: /:slug
  page: /:slug

plugins:
  - resolve: saber-plugin-query-posts