title: NS Resources
shortTitle: NSR
desc: Links and resources to help people serving National Service in Singapore.

# pages list
list:
  - name: General
    slug: general
    pages:
      - faq
      - contact
      - lingo
      - commands
      - ranks
      - free-time
      - songs
  - name: BMT
    slug: bmt
    pages:
      - enlistment-tips
      - sar21
      - hg
      - cqb
      - fieldcamp
      - bic
      - pop
      - cpr-aed
  - name: Vocations
    slug: vocations
    pages:
      - transport
      - infantry
      - asa
  - name: Site
    slug: site
    pages:
      - improve
      - contribute

# sidebar links
links:
  - name: SG subreddit
    class: red
    url: https://www.reddit.com/r/singapore
  - name: NS subreddit
    class: red
    url: https://www.reddit.com/r/nationalservicesg
  - name: NS discord
    class: black
    url: https://discord.gg/jZzsPGS
  - name: NS Portal
    class: green
    url: https://www.ns.sg/nsp/portal/site/mindef-nsf
  - name: SAF Health
    class: green
    link: https://www.safhealth.gov.sg/
  - name: GitHub
    class: black
    url: https://github.com/themindstorm/ns-links/