title: NS Resources
desc: Links and resources to help people serving National Service in Singapore.

# pages list
list:
  - name: General
    slug: general
    pages:
      - commands
      - ranks
      - free-time
  - name: BMT
    slug: bmt
    pages:
      - sar21
      - hg
      - cqb
      - fieldcamp
      - bic
      - pop
      - cpr-aed
  - name: Vocations
    slug: vocations
    pages:
      - transport
      - infantry
      - asa
  - name: Site
    slug: site
    pages:
      - improve